// <auto-generated />
namespace _0309一對多ccc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create2));
        
        string IMigrationMetadata.Id
        {
            get { return "202103090911388_create2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
